<?php

use SwaggerAssertions\PhpUnit\AssertsTrait;
use SwaggerAssertions\SchemaManager;

/**
 * PHPUnit integration example.
 */
class LocalFileBigTest extends \PHPUnit\Framework\TestCase
{
    use AssertsTrait;

    static $paths = [
        '/codemap/appinfo',
        '/codemap/definitions',
        '/codemap/definitions/{structure}',
        '/codemap/flushcache',
        '/codemap/map',
        '/codemap/map/{id}',
        '/codemap/maps',
        '/codemap/maps/{codemapSetId}',
        '/codemap/maps/{id}',
        '/codemap/mapsets',
        '/codemap/mapsets/{mapsetId}',
        '/codemap/mapsets/{sourceAANamespace}/{sourceCodesetName}/{destAANamespace}/{destCodesetName}',
        '/codemap/set',
        '/codemap/set/{id}',
        '/codemap/sets',
        '/codemap/sets/{id}',
        '/codemap/{tenant}/appinfo',
        '/codemap/{tenant}/definitions',
        '/codemap/{tenant}/definitions/{structure}',
        '/codemap/{tenant}/flushcache',
        '/codemap/{tenant}/map',
        '/codemap/{tenant}/map/{id}',
        '/codemap/{tenant}/maps',
        '/codemap/{tenant}/maps/{codemapSetId}',
        '/codemap/{tenant}/maps/{id}',
        '/codemap/{tenant}/mapsets',
        '/codemap/{tenant}/mapsets/{mapsetId}',
        '/codemap/{tenant}/mapsets/{sourceAANamespace}/{sourceCodesetName}/{destAANamespace}/{destCodesetName}',
        '/codemap/{tenant}/set',
        '/codemap/{tenant}/set/{id}',
        '/codemap/{tenant}/sets',
        '/codemap/{tenant}/sets/{id}',
        '/codeset/appinfo',
        '/codeset/assigningauthorities',
        '/codeset/assigningauthorities/{fromNamespace}/codesets/{name}/copyto/assigningauthorities/{toNamespace}',
        '/codeset/assigningauthorities/{namespace}',
        '/codeset/assigningauthorities/{namespace}/codes',
        '/codeset/assigningauthorities/{namespace}/codesets',
        '/codeset/assigningauthorities/{namespace}/codesets/{name}',
        '/codeset/assigningauthorities/{namespace}/codesets/{name}/codes',
        '/codeset/assigningauthorities/{namespace}/codesets/{name}/codes/{code}',
        '/codeset/assigningauthorities/{namespace}/codesets/{name}/codes/{id}',
        '/codeset/assigningauthority/{fromId}/codesets/{name}/copyto/assigningauthority/{toId}',
        '/codeset/assigningauthority/{id}',
        '/codeset/assigningauthority/{id}/codes',
        '/codeset/assigningauthority/{id}/codesets',
        '/codeset/assigningauthority/{id}/codesets/{name}',
        '/codeset/assigningauthority/{id}/codesets/{name}/codes',
        '/codeset/assigningauthority/{id}/codesets/{name}/codes/{code}',
        '/codeset/assigningauthoritybyoid/{oid}',
        '/codeset/code/{id}',
        '/codeset/codes',
        '/codeset/codes/{id}',
        '/codeset/codeset/{fromCodesetId}/copyto/assigningauthorities/{toNamespace}',
        '/codeset/codeset/{fromCodesetId}/copyto/assigningauthority/{toAssigningAuthorityId}',
        '/codeset/codeset/{id}',
        '/codeset/codeset/{id}/codes',
        '/codeset/codeset/{id}/codes/{code}',
        '/codeset/codesets',
        '/codeset/definitions',
        '/codeset/definitions/{structure}',
        '/codeset/flushcache',
        '/codeset/{tenant}/appinfo',
        '/codeset/{tenant}/assigningauthorities',
        '/codeset/{tenant}/assigningauthorities/{fromNamespace}/codesets/{name}/copyto/assigningauthorities/{toNamespace}',
        '/codeset/{tenant}/assigningauthorities/{namespace}',
        '/codeset/{tenant}/assigningauthorities/{namespace}/codes',
        '/codeset/{tenant}/assigningauthorities/{namespace}/codesets',
        '/codeset/{tenant}/assigningauthorities/{namespace}/codesets/{name}',
        '/codeset/{tenant}/assigningauthorities/{namespace}/codesets/{name}/codes',
        '/codeset/{tenant}/assigningauthorities/{namespace}/codesets/{name}/codes/{code}',
        '/codeset/{tenant}/assigningauthorities/{namespace}/codesets/{name}/codes/{id}',
        '/codeset/{tenant}/assigningauthority/{fromId}/codesets/{name}/copyto/assigningauthority/{toId}',
        '/codeset/{tenant}/assigningauthority/{id}',
        '/codeset/{tenant}/assigningauthority/{id}/codes',
        '/codeset/{tenant}/assigningauthority/{id}/codesets',
        '/codeset/{tenant}/assigningauthority/{id}/codesets/{name}',
        '/codeset/{tenant}/assigningauthority/{id}/codesets/{name}/codes',
        '/codeset/{tenant}/assigningauthority/{id}/codesets/{name}/codes/{code}',
        '/codeset/{tenant}/assigningauthoritybyoid/{oid}',
        '/codeset/{tenant}/code/{id}',
        '/codeset/{tenant}/codes',
        '/codeset/{tenant}/codes/{id}',
        '/codeset/{tenant}/codeset/{fromCodesetId}/copyto/assigningauthorities/{toNamespace}',
        '/codeset/{tenant}/codeset/{fromCodesetId}/copyto/assigningauthority/{toAssigningAuthorityId}',
        '/codeset/{tenant}/codeset/{id}',
        '/codeset/{tenant}/codeset/{id}/codes',
        '/codeset/{tenant}/codeset/{id}/codes/{code}',
        '/codeset/{tenant}/codesets',
        '/codeset/{tenant}/definitions',
        '/pet/findByStatus',
        '/codeset/{tenant}/definitions/{structure}',
        '/codeset/{tenant}/flushcache',
        '/eventnotifier/appInfo',
        '/eventnotifier/communication',
        '/eventnotifier/communication/{id}',
        '/eventnotifier/communications',
        '/eventnotifier/definitions',
        '/eventnotifier/definitions/{structure}',
        '/eventnotifier/dnd',
        '/eventnotifier/dnd/{id}',
        '/eventnotifier/dnds',
        '/eventnotifier/hashtag',
        '/eventnotifier/hashtag/{id}',
        '/eventnotifier/hashtag/{tag}',
        '/eventnotifier/hashtagid',
        '/eventnotifier/hashtagid/{id}',
        '/eventnotifier/hashtagid/{name}',
        '/eventnotifier/hashtagids',
        '/eventnotifier/hashtags',
        '/eventnotifier/subscriber',
        '/eventnotifier/subscriber/{id}',
        '/eventnotifier/subscribers',
        '/eventnotifier/subscription',
        '/eventnotifier/subscription/{id}',
        '/eventnotifier/subscription/{id}/behaviorCode',
        '/eventnotifier/subscriptions',
        '/eventnotifier/{tenant}/appInfo',
        '/eventnotifier/{tenant}/communication',
        '/eventnotifier/{tenant}/communication/{id}',
        '/eventnotifier/{tenant}/communications',
        '/eventnotifier/{tenant}/definitions',
        '/eventnotifier/{tenant}/definitions/{structure}',
        '/eventnotifier/{tenant}/dnd',
        '/eventnotifier/{tenant}/dnd/{id}',
        '/eventnotifier/{tenant}/dnds',
        '/eventnotifier/{tenant}/hashtag',
        '/eventnotifier/{tenant}/hashtag/{id}',
        '/eventnotifier/{tenant}/hashtag/{tag}',
        '/eventnotifier/{tenant}/hashtagid',
        '/eventnotifier/{tenant}/hashtagid/{id}',
        '/eventnotifier/{tenant}/hashtagid/{name}',
        '/eventnotifier/{tenant}/hashtagids',
        '/eventnotifier/{tenant}/hashtags',
        '/eventnotifier/{tenant}/subscriber',
        '/eventnotifier/{tenant}/subscriber/{id}',
        '/eventnotifier/{tenant}/subscribers',
        '/eventnotifier/{tenant}/subscription',
        '/eventnotifier/{tenant}/subscription/{id}',
        '/eventnotifier/{tenant}/subscription/{id}/behaviorCode',
        '/eventnotifier/{tenant}/subscriptions',
        '/eventnotifiercollector/appInfo',
        '/eventnotifiercollector/definitions',
        '/eventnotifiercollector/definitions/{structure}',
        '/eventnotifiercollector/entries',
        '/eventnotifiercollector/entry',
        '/eventnotifiercollector/entry/{id}',
        '/eventnotifiercollector/entry/{id}/entryRead',
        '/eventnotifiercollector/{tenant}/appInfo',
        '/eventnotifiercollector/{tenant}/definitions',
        '/eventnotifiercollector/{tenant}/definitions/{structure}',
        '/eventnotifiercollector/{tenant}/entries',
        '/eventnotifiercollector/{tenant}/entry',
        '/eventnotifiercollector/{tenant}/entry/{id}',
        '/eventnotifiercollector/{tenant}/entry/{id}/entryRead',
        '/monitor/flushcache/{whichcache}',
        '/monitor/healthcheck',
        '/monitor/messagebrokers',
        '/monitor/minpollseconds',
        '/monitor/nodes',
        '/monitor/nodes/{name}',
        '/monitor/nodes/{name}/history',
        '/monitor/nodes/{name}/messagebrokers',
        '/monitor/nodes/{name}/messagebrokers/{brokerId}/queues/{name}/messages',
        '/monitor/nodes/{name}/messagebrokers/{brokerId}/queues/{name}/messages/{msgId}',
        '/monitor/nodes/{name}/rawhistory',
        '/monitor/nodes/{name}/rawstats',
        '/monitor/nodes/{name}/routes',
        '/monitor/nodes/{name}/routes/{routeName}/status',
        '/monitor/rawstats',
        '/monitor/refresher',
        '/ngmsrest/appinfo',
        '/ngmsrest/types/{msgType}/submit',
        '/ngmsresubmit/appinfo',
        '/ngmsresubmit/resubmit/nodes/{ngsSourceNodeName}/queues/{jmsSourceQueueName}/resubmitter',
        '/nodemanager/appinfo',
        '/nodemanager/definitions/{structure}',
        '/nodemanager/mynode',
        '/nodemanager/node',
        '/nodemanager/node/{id}',
        '/nodemanager/nodes',
        '/nodemanager/nodes/{name}',
    ];

    public function testFetchPetBodyMatchDefinition()
    {
        $filePath = __DIR__ . '/../fixtures/big.json';

        $ref = new \SwaggerAssertions\JsonSchema\RefResolver(
            new \SwaggerAssertions\JsonSchema\Uri\UriRetriever(),
            new \SwaggerAssertions\JsonSchema\Uri\UriResolver()
        );

        $resolve = $ref->resolveSkeleton('file://' . $filePath);

        // Use file:// for local files
        $schema = new SchemaManager($resolve);

        $this->assertCount(191, $schema->getPathTemplates());

        foreach (self::$paths as $path) {
            $schema->getRequestParameters($path,'get');
        }
    }
}
